[package]
name = "tstream"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
clap = { version = "4.3.5", features = ["derive", "unstable-styles"] }
env_logger = "0.9.0"
log = "0.4.17"
rpassword = "5.0"
